
// This file was auto-generated by ML.NET Model Builder. 

using TravelModell_APP;

// Create single instance of sample data from first line of dataset for model input
TravelModell.ModelInput sampleData = new TravelModell.ModelInput()
{
    Col0 = @"陰天",
    Col1 = @"慢跑",
    Col2 = @"瑜珈",
    Col3 = @"滑雪",
    Col4 = @"捷克",
};



Console.WriteLine("Using model to make single prediction -- Comparing actual Col5 with predicted Col5 from sample data...\n\n");


Console.WriteLine($"Col0: {@"陰天"}");
Console.WriteLine($"Col1: {@"慢跑"}");
Console.WriteLine($"Col2: {@"瑜珈"}");
Console.WriteLine($"Col3: {@"滑雪"}");
Console.WriteLine($"Col4: {@"捷克"}");
Console.WriteLine($"Col5: {@"宜蘭縣"}");


var sortedScoresWithLabel = TravelModell.PredictAllLabels(sampleData);
Console.WriteLine($"{"Class",-40}{"Score",-20}");
Console.WriteLine($"{"-----",-40}{"-----",-20}");

foreach (var score in sortedScoresWithLabel)
{
    Console.WriteLine($"{score.Key,-40}{score.Value,-20}");
}

Console.WriteLine("=============== End of process, hit any key to finish ===============");
Console.ReadKey();

